# Generated by Django 4.0.6 on 2022-07-25 17:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('author', '0001_initial'),
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=180)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('page', models.PositiveIntegerField()),
                ('producer', models.CharField(max_length=180)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='author.author')),
                ('catalog', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='catalog.catalog')),
            ],
        ),
    ]
